#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"


system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ "$system_type" = "Linux" ]; then
  is_ish=$(uname -v)
  if [[ "${is_ish:0:3}" = iSH ]]; then
    echo "s iSH"
    apk update && apk upgrade
  fi
  if command -v apt >/dev/null 2>&1; then
    echo "Ubuntu"
  fi
fi

if command -v yadm >/dev/null 2>&1; then
  echo "Init submodules"
  yadm submodule update --recursive --init
fi
